Setup all the Entities #40013
Roshan-successive/javascript-server pull request #17
Opened 2020-11-17 10:35 UTC by Roshan-successive

- Learned about model setups and seed.
- Model setup with initial seed.
- Set up all entities.

2020-11-17 10:43 UTC, iamsuraj28 approved these changes

2020-11-17 10:43 UTC, iamsuraj28 commented on .env
> +secret_key=qwertyuiopasdfghjklzxcvbnm123456
delete this file from PR

2020-11-17 10:46 UTC, iamsuraj28 commented on .env
> +secret_key=qwertyuiopasdfghjklzxcvbnm123456
remove this from PR

2020-11-17 10:46 UTC, iamsuraj28 requested changes
Do the required changes.

2020-11-17 11:39 UTC, Roshan-successive commented on .env
> +secret_key=qwertyuiopasdfghjklzxcvbnm123456
Deleted .env file

2020-11-17 11:40 UTC, Roshan-successive commented on .env
> +secret_key=qwertyuiopasdfghjklzxcvbnm123456
Removed .env file from the PR

2020-11-19 05:32 UTC, iamsuraj28 approved these changes

2020-11-19 05:32 UTC, merged